baseURL = 'https://log.vexation.ca/'
languageCode = 'en-us'
title = 'VeXation'
theme = "mini"
copyright = "Daniel McCarney"
enableEmoji = true
#enableGitInfo = true

[markup]
  [markup.highlight]
    style = 'monokai'
    tabwidth = 2
  [markup.goldmark.renderer]
    unsafe = false
  [markup.tableOfContents]
    endLevel = 2
    ordered = false
    startLevel = 1

[social]
  github = 'https://github.com/cpu/vexation'
  twitter = 'https://twitter.com/cpu'

[permalinks]
  posts = '/:year/:month/:title'

[params]
  author = 'Daniel McCarney'
  description = "VeXation: writing a from-scratch Win95 virus with Borland Turbo Assembler."
  enableRSS = true
  showToc = true
  showPowerBy = false
  hiddenPostSummaryInHomePage = false
  customCSS = [ 'css/custom.css' ]
  images = [ "/2019/01/getting-set-up/win95.get.hype.small.jpg" ]
