# Link Checker Workflow for PRs/Pushes.
# Uses 'fail:true' and blocks merge of broken links.
name: Check Links

on:
  push:
  pull_request:

jobs:
  linkcheck:
    name: Run Lychee Linkchecker
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./site
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Nix Flakes doesn't work on shallow clones

      - name: Install Nix
        uses: cachix/install-nix-action@v21

      - name: Build static site
        run: nix build

      - name: Restore lychee cache
        uses: actions/cache@v3
        with:
          path: .lycheecache
          key: cache-lychee-${{ github.sha }}
          restore-keys: cache-lychee-

      - name: Check links
        uses: lycheeverse/lychee-action@v1.7.0
        with:
          args: "--verbose \
                 --cache \
                 --max-cache-age 1d \
                 --exclude-mail \
                 'site/result/**/*.md' 'site/result/**/*.html'"
          fail: true
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
